function [icent,jcent] = sssHiC(data,bw) 

paramstruct = struct('stype',2,...
                         'alpha',0.05,...
                         'imovie',0,...
                         'hmin',bw,...
                         'hmax',bw,...
                         'igrid',1);

[icent,jcent] =sssHiC_peak_computation(data,paramstruct);



